apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ lower .Values.labName | splitList " " | join "-" }}-common
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: {{ .Values.flexVolume.driver }}
    options:
      monitors: {{ .Values.flexVolume.options.monitors }}
      share: '/common'
      authid: {{ .Values.flexVolume.options.authid }}
      mds: {{ .Values.flexVolume.options.mds }}
      keyring: {{ .Values.flexVolume.options.keyring }}
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ lower .Values.labName | splitList " " | join "-" }}-common
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ lower .Values.labName | splitList " " | join "-" }}-common
  resources:
    requests:
      storage: 1Ti
