apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ lower .Values.labName | splitList " " | join "-" }}
  namespace: {{ lower .Values.labName | splitList " " | join "-" }}
spec:
  hard:
    limits.cpu: "{{ .Values.cpu }}"
    limits.memory: {{ .Values.memory }}
{{- with .Values.gpu }}
{{- range $i, $v := . }}
    requests.nvidia.com/gpu-{{ $i }}: "{{ $v }}"
{{- end }}
{{- end }}