apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: super-admin-service-account
    addonmanager.kubernetes.io/mode: Reconcile
  name: super-admin-service-account
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: super-admin-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: super-admin-service-account
  namespace: kube-system