kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gpu-cluster-operator
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/status
  resourceNames:
  - gpu-test
  verbs:
  - get
  - list
  - watch
