apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod-applied
spec:
  nodeSelector:
    usage: dev
  containers:
  - name: kubernetes-pause
    command:
      - bash
      - -c
      - "while true; do sleep 10; done"
    image: registry.bst-1.cns.bstjpc.com:5000/dbelt/mysql-ms-mysql-v5.6-v0.2.0:20171107
    resources:
      requests:
        cpu: 4000m
        memory: 1Gi
      limits:
        nvidia.com/gpu-k80: "1"