apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - default:
      cpu: 4
      memory: 4Gi
      nvidia.com/gpu: 1
    defaultRequest:
      cpu: 1
      memory: 1Gi
      nvidia.com/gpu: 1
    type: Container
