apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gpu-operator
  namespace: gpu-test
rules:
- apiGroups: [""]
  resources: ["pods", "events", "pods/log", "pods/status", "configmaps", "pods/exec"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update"]
