apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    kube-app: gpu-test
  name: consul
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        kube-app: gpu-test
    spec:
      containers:
      - command:
        - bash
        - -c
        - "while true; do sleep 10; done"
        image: registry.bst-1.cns.bstjpc.com:5000/dbelt/mysql-ms-mysql-v5.6-v0.2.0:20171107
        name: gpu-test
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
      restartPolicy: Always
status: {}
