apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    name: test-pod-applied
  namespace: gpu-test
spec:
  containers:
  - name: kubernetes-pause
    command:
      - bash
      - -c
      - "while true; do sleep 10; done"
    image: registry.bst-1.cns.bstjpc.com:5000/dbelt/mysql-ms-mysql-v5.6-v0.2.0:20171107
    resources:
      requests:
        cpu: 300m
        memory: 1300Mi
        nvidia.com/gpu: "1"
      limits:
        cpu: 300m
        memory: 1300Mi
        nvidia.com/gpu: "1"