apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-jupyter
  namespace: gpu-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-jupyter
    spec:
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-384/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-384
        name: lib
      containers:
      - name: tensorflow
        image: registry.bst-1.cns.bstjpc.com:5000/tensorflow/tensorflow:0.11.0rc0-gpu
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: 1
            memory: 1Gi
            nvidia.com/gpu-k20m: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
