apiVersion: v1
kind: Service
metadata:
  name: tf-jupyter-service
  namespace: gpu-test
  labels:
    app: tf-jupyter
spec:
  selector:
    app: tf-jupyter
  ports:
  - port: 8888
    protocol: TCP
    nodePort: 31222
  type: NodePort
