apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "test-pv.fullname" . }}
  labels:
    app: {{ template "test-pv.name" . }}
    chart: {{ template "test-pv.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "test-pv.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "test-pv.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: gluster-volume
        persistentVolumeClaim:
          claimName: {{ .Values.pv.claimName }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - sh
          - -c
          - "while true; do sleep 3600; done"
          volumeMounts:
          - name: gluster-volume
            mountPath: {{ .Values.pv.mountPath }}
            readOnly: false
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
