apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-standalone-config-cm
  labels:
    app: minio-standalone
data:
    config.json: |-
      {
        "version": "20",
        "credential": {
          "accessKey": "AKIAIOSFODNN7EXAMPLE",
          "secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        },
        "region": "us-east-1",
        "browser": "on",
        "domain": "",
        "logger": {
          "console": {
            "enable": true
          },
          "file": {
            "enable": false,
            "fileName": ""
          }
        },
        "notify": {
          "amqp": {
            "1": {
              "enable": false,
              "url": "",
              "exchange": "",
              "routingKey": "",
              "exchangeType": "",
              "deliveryMode": 0,
              "mandatory": false,
              "immediate": false,
              "durable": false,
              "internal": false,
              "noWait": false,
              "autoDeleted": false
            }
          },
          "nats": {
            "1": {
              "enable": false,
              "address": "",
              "subject": "",
              "username": "",
              "password": "",
              "token": "",
              "secure": false,
              "pingInterval": 0,
              "streaming": {
                "enable": false,
                "clusterID": "",
                "clientID": "",
                "async": false,
                "maxPubAcksInflight": 0
              }
            }
          },
          "elasticsearch": {
            "1": {
              "enable": false,
              "format": "namespace",
              "url": "",
              "index": ""
            }
          },
          "redis": {
            "1": {
              "enable": false,
              "format": "namespace",
              "address": "",
              "password": "",
              "key": ""
            }
          },
          "postgresql": {
            "1": {
              "enable": false,
              "format": "namespace",
              "connectionString": "",
              "table": "",
              "host": "",
              "port": "",
              "user": "",
              "password": "",
              "database": ""
            }
          },
          "kafka": {
            "1": {
              "enable": false,
              "brokers": null,
              "topic": ""
            }
          },
          "webhook": {
            "1": {
              "enable": false,
              "endpoint": ""
            }
          },
          "mysql": {
            "1": {
              "enable": false,
              "format": "namespace",
              "dsnString": "",
              "table": "",
              "host": "",
              "port": "",
              "user": "",
              "password": "",
              "database": ""
            }
          },
          "mqtt": {
            "1": {
              "enable": false,
              "broker": "",
              "topic": "",
              "qos": 0,
              "clientId": "",
              "username": "",
              "password": ""
            }
          }
        }
      }

