apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: minio-standalone
  labels:
    app: minio-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-standalone
  template:
    metadata:
      name: minio-standalone
      labels:
        app: minio-standalone
    spec:
      nodeSelector:
        type: triton
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
        - name: export
          emptyDir: {}
      containers:
        - name: minio
          image: registry.bst-1.cns.bstjpc.com:5000/minio/minio:RELEASE.2016-11-26T02-23-47Z
          args: ["server", "/export"]
          volumeMounts:
            - name: export
              mountPath: /export
            - name: podinfo
              mountPath: /podinfo
              readOnly: false
          ports:
            - name: service
              containerPort: 9000
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-standalone-user
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-standalone-user
                  key: secretkey
          livenessProbe:
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
