apiVersion: v1
kind: Service
metadata:
  name: deploy-heketi
  labels:
    glusterfs: heketi-service
    deploy-heketi: suppport
  annotations:
    description: Exposes Heketi Service
spec:
  selector:
    name: deploy-heketi
  ports:
  - name: deploy-heketi
    port: 8080
    nodePort: 32666
  type: NodePort