apiVersion: v1
kind: Pod
metadata:
  name: pod-use-pvc
spec:
  nodeSelector:
    type: master
  containers:
  - name: pod-use-pvc
    image: registry.bst-1.cns.bstjpc.com:5000/gcr.io/google_containers/busybox
    command:
    - sh
    - -c
    - "while true; do sleep 3600; done"
    volumeMounts:
    - name: gluster-volume
      mountPath: "/pv-data"
      readOnly: false
  volumes:
  - name: gluster-volume
    persistentVolumeClaim:
      claimName: pvc-gluster-heketi