apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mfs-test-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
  selector:
    matchLabels:
      type: shared