apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /root/gitSwarm/dbcm-base-managers/compose/consul.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  ports:
  - name: "8500"
    port: 8500
    targetPort: 8500
  - name: "8300"
    port: 8300
    targetPort: 8300
  - name: "8301"
    port: 8301
    targetPort: 8301
  - name: "8302"
    port: 8302
    targetPort: 8302
  - name: "8400"
    port: 8400
    targetPort: 8400
  selector:
    io.kompose.service: consul
status:
  loadBalancer: {}
