apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /root/gitSwarm/dbcm-base-managers/compose/mysql.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  ports:
  - name: "9104"
    port: 9104
    targetPort: 9104
  - name: "9100"
    port: 9100
    targetPort: 9100
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
