apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-lab-1-user2
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 2Gi
  selector:
    matchLabels:
      type: "test-lab-1-user2"
