---
- hosts: k8s-nodes
  gather_facts: no
  tasks:

  - name: check
    shell: "echo $(ifconfig flannel0 |grep -oP '(?<=inet ).*(?=.[0-9]  netmask 255)') && echo $(ifconfig docker0 |grep -oP '(?<=inet ).*(?=.[0-9]  netmask 255)')"


