apiVersion: v1
kind: Service
metadata:
  name: conductor-ui
  labels:
    k8s-app: conductor-ui
spec:
  selector:
    k8s-app: conductor-ui
  ports:
  - port: 5000
    nodePort: 31666
  type: NodePort
