apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-test-pv-claim-1
  labels:
    app: csi-test-pv-claim-1
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi