apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fio-test-csi-1
  labels:
    app: fio-test-csi-1
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fio-test-csi-1
    spec:
      containers:
      - image: clusterhq/fio-tool:latest
        name: fio
        command:
        - bash
        - -c
        - "tail -f /dev/null"
        volumeMounts:
        - name: fio-test-pv
          mountPath: /data
      volumes:
      - name: fio-test-pv
        persistentVolumeClaim:
          claimName: csi-test-pv-claim-1
