{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "linux-centos7",
    "namespace": "default",
    "selfLink": "/apis/extensions/v1beta1/namespaces/default/deployments/linux-centos7",
    "uid": "83a6ef9e-2b11-11e8-a0e6-90b8d0599f2f",
    "resourceVersion": "1038880",
    "generation": 2,
    "creationTimestamp": "2018-03-19T01:04:45Z",
    "labels": {
      "app": "linux-centos7"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "2"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "linux-centos7"
      }
    },
    "template": {
      "metadata": {
        "name": "linux-centos7",
        "creationTimestamp": null,
        "labels": {
          "app": "linux-centos7"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "linux-centos7",
            "image": "registry.bst-1.cns.bstjpc.com:5000/centos:7.4",
            "command": [
              "bash",
              "-c",
              "while true; do sleep 10; done"
            ],
            "resources": {
              "requests": {
                "memory": "256Mi"
              }
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent",
            "securityContext": {
              "privileged": false
            }
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": "25%",
        "maxSurge": "25%"
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 600
  },
  "status": {
    "observedGeneration": 2,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2018-03-19T01:07:15Z",
        "lastTransitionTime": "2018-03-19T01:07:15Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      },
      {
        "type": "Progressing",
        "status": "True",
        "lastUpdateTime": "2018-03-19T01:07:15Z",
        "lastTransitionTime": "2018-03-19T01:04:45Z",
        "reason": "NewReplicaSetAvailable",
        "message": "ReplicaSet \"linux-centos7-655896d8f9\" has successfully progressed."
      }
    ]
  }
}