apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "registry-ui.fullname" . }}
  labels:
    app: {{ template "registry-ui.name" . }}
    chart: {{ template "registry-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "registry-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "registry-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: REGISTRY_HOST
            value: {{ .Values.registry.host }}
          - name: REGISTRY_PORT
            value: "{{ .Values.registry.port }}"
          - name: REGISTRY_PROTOCOL
            value: {{ .Values.registry.protocol }}
          - name: SSL_VERIFY
            value: "{{ .Values.registry.ssl_verify }}"
          - name: ALLOW_REGISTRY_LOGIN
            value: "{{ .Values.registry.allow_login }}"
          - name: REGISTRY_ALLOW_DELETE
            value: "{{ .Values.registry.allow_delete }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
