# Default values for commit-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.bst-1.cns.bstjpc.com:5000/docker-commit-push
  tag: "20180530"
  pullPolicy: IfNotPresent
#  init: registry.bst-1.cns.bstjpc.com:5000/get-container-id:20180528

labName: Intelligent Data Lab
timeout: 300
targetReleaseName: "hongchao.ma-dev1"
imageName: "registry.bst-1.cns.bstjpc.com:5000/test-name"
imageTag: ""
author: ""
message: ""