apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-intelligence-labfs-root
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: srcb/cephfs
    options:
      monitors: ceph-mon1:6789,ceph-mon2:6789,ceph-mon3:6789,ceph-mon4:6789,ceph-mon5:6789
#      share: '/system_common'
      share: '/'
      authid: 'admin'
      mds: 'Data_Intelligence_Labfs'
      keyring: 'AQDeUgJbJgwNMhAAnzeW5LwQSwqMyWs7Zvl5cQ=='
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-intelligence-labfs-root
spec:
  accessModes:
    - ReadWriteMany
  volumeName: data-intelligence-labfs-root
  resources:
    requests:
      storage: 1024Gi

