apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: data-intelligence-labfs-root2
  labels:
    app: data-intelligence-labfs-root2
spec:
  template:
    metadata:
      labels:
        app: data-intelligence-labfs-root2
    spec:
      containers:
      - image: registry.bst-1.cns.bstjpc.com:5000/clusterhq/fio-tool:latest
        name: fio
        command:
        - bash
        - -c
        - "tail -f /dev/null"
        volumeMounts:
        - name: fio-test-pv
          mountPath: /data
      volumes:
      - name: fio-test-pv
        flexVolume:
          driver: srcb/cephfs
          options:
            monitors: 109.105.1.208:6789,109.105.1.209:6789,109.105.1.253:6789,109.105.1.254:6789,109.105.30.157:6789
      #      share: '/system_common'
            share: '/'
            authid: 'admin'
            mds: 'Data_Intelligence_Labfs'
            keyring: 'AQDeUgJbJgwNMhAAnzeW5LwQSwqMyWs7Zvl5cQ=='

