apiVersion: v1
kind: ServiceAccount
metadata:
  name: intelligent-innovation-lab-viewer
  namespace: intelligent-innovation-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gpu-operator-viewer
  namespace: intelligent-innovation-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: intelligent-innovation-lab-viewer
  namespace: intelligent-innovation-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
subjects:
- kind: ServiceAccount
  name: intelligent-innovation-lab-viewer
  namespace: intelligent-innovation-lab
roleRef:
  kind: Role
  name: gpu-operator-viewer
  apiGroup: rbac.authorization.k8s.io
