apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: gcloud-system
  namespace: rook
spec:
  replicated:
    # 副本数
    size: 2
  # For an erasure-coded pool, comment out the replication size above and uncomment the following settings.
  # Make sure you have enough OSDs to support the replica size or erasure code chunks.
  #erasureCoded:
    dataChunks: 1
    codingChunks: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-gcloud-system
provisioner: rook.io/block
parameters:
  pool: gcloud-system
  # Specify the Rook cluster from which to create volumes.
  # If not specified, it will use `rook` as the name of the cluster.
  # This is also the namespace where the cluster will be
  clusterName: rook
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: ext4
#  fstype: xfs