apiVersion: v1
kind: ServiceAccount
metadata:
  name: machine-learning-lab-admin
  namespace: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gpu-operator-admin
  namespace: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/status
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-learning-lab
  namespace: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
subjects:
- kind: ServiceAccount
  name: machine-learning-lab-admin
  namespace: machine-learning-lab
roleRef:
  kind: Role
  name: gpu-operator-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machine-learning-lab
subjects:
- kind: ServiceAccount
  name: machine-learning-lab-admin
  namespace: machine-learning-lab