apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config
  namespace: kube-admin
data:
  storageClassMap: |
    fast-disks:
       hostDir: /mnt/fast-disks
       mountDir:  /mnt/fast-disks
       blockCleanerCommand:
         - "/scripts/shred.sh"
         - "2"
       volumeMode: Filesystem
       fsType: ext4
       namePattern: "*"