apiVersion: v1
kind: Service
metadata:
  name: local-volume-provisioner
  namespace: kube-admin
  labels:
    app: local-volume-provisioner
spec:
  type: ClusterIP
  selector:
    app: local-volume-provisioner
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
