apiVersion: v1
kind: Pod
metadata:
  name: alpine1
  namespace: default
  annotations:
    cmd: kubectl exec alpine1 -- nslookup kubernetes-dashboard.kube-system
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-m3
  containers:
  - name: busybox
    image: registry.bst-1.cns.bstjpc.com:5000/alpine:3.6
    command:
    - sh
    - -c
    - "tail -f /dev/null"
    imagePullPolicy: IfNotPresent
