apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: default
  annotations:
    cmd: kubectl exec busybox2 -- nslookup kubernetes-dashboard.kube-system
spec:
  hostNetwork: true
  containers:
  - name: busybox2
    image: registry.bst-1.cns.bstjpc.com:5000/gcr.io/google_containers/busybox
    command:
    - sh
    - -c
    - "tail -f /dev/null"
    imagePullPolicy: IfNotPresent
