apiVersion: v1
kind: Secret
metadata:
  name: sshd-test3
  namespace: intelligent-data-lab
type: Opaque
data:
  authorized_keys: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDOCt1K0orOGFjbithTDZtK2hrM0tibEoxb2tsdDJSTjkyM1ptTlMzT0NjMGcrTDhaWjhCSHBaSElNaitmZ0lIWEdQQ0l6Z1o0VVFDMEhOL1dSMmxlRmZFT2pnMUdFOHdyZE1kNVpzVkREaFhaMFJncUZwakVhdmxYYzVWSHZFWVVOUkMvYlBlSEZPRDZhNG8zSUM3ZEJRTW9HWGdvRUkxamZ2NVpQME12L1R4Rmd6RkNUWGFTYUF6aUJySkVyQ3MyMURkK0RPTllmSnk3QmZieFdIclgvVk1wN1hHTTFTcnp2NUxKRFd1L0kzc2FsS2lvUTBhMG1YcFExUkNwdVhWcXJ0azB4MmQ5OHNLYkFUN3JJcVo2MXlTQ3ViYVRXZWFkZUhaSGMwQ3FaUWxNVXlsRXIzWEFDbDE2Z3Nscys2NXhmQnMvWjlrYzRYWGpENjkyT2tFNU4gcm9vdEBtaGM=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sshd-test3
  namespace: intelligent-data-lab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sshd-test3
    spec:
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-384/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-384
        name: lib
      - name: ssh-key
        secret:
          secretName: sshd-test3
      containers:
      - name: sshd
#        image: registry.bst-1.cns.bstjpc.com:5000/ubuntu-sshd:14.04
        image: registry.bst-1.cns.bstjpc.com:5000/tensorflow-sshd:0.11.0rc0-gpu
        ports:
        - containerPort: 22
        - containerPort: 8888
        resources:
          limits:
            cpu: 1
            memory: 1Gi
            nvidia.com/gpu-p40: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
        - mountPath: /root/.ssh
          name: ssh-key
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: sshd-test-service3
  namespace: intelligent-data-lab
  labels:
    app: sshd-test3
spec:
  selector:
    app: sshd-test3
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    nodePort: 32227
  - name: jupyter
    port: 8888
    protocol: TCP
    nodePort: 32228
  type: NodePort
