apiVersion: v1
kind: ConfigMap
metadata:
  name: k20-use001
  namespace: intelligent-data-lab
data:
  authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAonk9Rdc8EYMKXW8I3qFc9/fyNsRi4dZombBg6ikyKLvdVtLt6zQ03rw+g66qlKJ3paheVA3vVr1X8cWkqB6ulO1bMFOq7Y1i1fYz21QbParityYA44XRgZ5yJSzKJ9LlfWP3O6PBBzt1UC9hL5twKgRiCVYPyveObP6+R7Uo7TYMtXIcQGxzH8YVuoxVqiLcHfq93C/UGuzGbYHoOn/cGDUgf7a7WBk5rx2GCXW9ue6ILVVorACqYNAHJiAGKomYjsg4ehW2aThNxo8SqeKRnOen/yXMnZHk9C6c+sVZXUz03j7ViQyOk47dEwvEYRquzqnOcw0O1ocDmS96N0eP6w== rsa-key-20180404
#    authorized_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8+u+J+8acn+aL6m+hk3KblJ1oklt2RN923ZmNS3OCc0g+L8ZZ8BHpZHIMj+fgIHXGPCIzgZ4UQC0HN/WR2leFfEOjg1GE8wrdMd5ZsVDDhXZ0RgqFpjEavlXc5VHvEYUNRC/bPeHFOD6a4o3IC7dBQMoGXgoEI1jfv5ZP0Mv/TxFgzFCTXaSaAziBrJErCs21Dd+DONYfJy7BfbxWHrX/VMp7XGM1Srzv5LJDWu/I3salKioQ0a0mXpQ1RCpuXVqrtk0x2d98sKbAT7rIqZ61ySCubaTWeadeHZHc0CqZQlMUylEr3XACl16gsls+65xfBs/Z9kc4XXjD692OkE5N root@mhc\nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCp9cW9cAtqKWuswRrgXx3vRLGUVl8By6SjQWhBg/sU9+iZtEWGKUWbSofg98HDEJ6FP2Nb0zY+vKe08ARBseAZqHUcjyFLCTaUPLYLgq7m22NHvUz6x3yD1O84B5w1QAJQOK/aJ7Ih06akukkVCUcTXoXXM6gi6Pucu7rPZ5ArtC1oIYFFpzfSEL7dmKgNHOISkVdp0p3t0ApikM3myskZGgRdRhnSJctqe5E7Iz8jQzaXOKUfcJd3eAJa0+TocLeUD/zBNRxTe8AFasGTSsZY0kbXAxnyJCUMwuldqy33SO8l9uyo0PJX+H1kP2XLRZTpTiqs2/uwvuyYOcIQZjSp root@7dd70763-c067-6232-a90b-d6c1a9eef026
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k20-use001
  namespace: intelligent-data-lab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k20-use001
    spec:
      volumes:
      - hostPath:
          path: /usr/lib/nvidia-384/bin
        name: bin
      - hostPath:
          path: /usr/lib/nvidia-384
        name: lib
      - hostPath:
          path: /data/k20-use001
        name: data
      - name: ssh-key
        configMap:
          name: k20-use001
      containers:
      - name: caffe-sshd
        image: registry.bst-1.cns.bstjpc.com:5000/chaneyk/tensorflow-cuda9-cudnn7:latest-gpu-sshd
#        image: registry.bst-1.cns.bstjpc.com:5000/chaneyk/tensorflow-cuda9:latest-gpu-sshd
#        image: registry.bst-1.cns.bstjpc.com:5000/bvlc/caffe-sshd:gpu
#        image: registry.bst-1.cns.bstjpc.com:5000/ubuntu-sshd:14.04
#        image: registry.bst-1.cns.bstjpc.com:5000/tensorflow-sshd2:0.11.0rc0-gpu
        ports:
        - containerPort: 22
        - containerPort: 8888
        resources:
          limits:
#            cpu: 4
#            memory: 8Gi
#            nvidia.com/gpu-k20m: 2
            cpu: 60
            memory: 140Gi
            nvidia.com/gpu-k20m: 4
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
        - mountPath: /root/.ssh
          name: ssh-key
        - mountPath: /data
          name: data
---
apiVersion: v1
kind: Service
metadata:
  name: k20-use001
  namespace: intelligent-data-lab
  labels:
    app: k20-use001
spec:
  selector:
    app: k20-use001
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    nodePort: 32555
  - name: jupyter
    port: 8888
    protocol: TCP
    nodePort: 32556
  type: NodePort
