kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/status
  verbs:
  - get
  - list
  - watch
