apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machine-learning-lab
subjects:
- kind: ServiceAccount
  name: machine-learning-lab-admin
  namespace: machine-learning-lab

