apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-learning-lab
  namespace: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
subjects:
- kind: ServiceAccount
  name: machine-learning-lab-admin
  namespace: machine-learning-lab
roleRef:
  kind: Role
  name: gpu-operator-admin
  apiGroup: rbac.authorization.k8s.io