apiVersion: v1
kind: ServiceAccount
metadata:
  name: machine-learning-lab-admin
  namespace: machine-learning-lab
  annotations:
    department: 'SRC-Beijing Machine Learning LAB'
  labels:
    srcb-group: machine-learning
