apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: fio-test
  labels:
    app: fio-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fio-test
  template:
    metadata:
      labels:
        app: fio-test
    spec:
      imagePullSecrets:
        - name: ksyunregistrykey
      containers:
      - image: hub.kce.ksyun.com/ksyun/busybox:latest
        name: fio
        command:
        - sh
        - -c
        - "tail -f /dev/null"
        resources:
          limits:
            cpu: 300m
            memory: 500Mi


