apiVersion: v1
kind: Pod
metadata:
  name: pod-test
spec:
  shareProcessNamespace: true
  containers:
  - name: pod-test
    image: rds.registry.ksyun.com/common/net-tools:latest
    command:
    - sh
    - -c
    - "while true; do sleep 3600; done"
  - name: pod-test2
    image: rds.registry.ksyun.com/common/net-tools:latest
    command:
      - tail
      - -f
      - /dev/null