apiVersion: v1
kind: Pod
metadata:
  name: pod-test2
spec:
  shareProcessNamespace: true
  containers:
  - name: pod-test2
    image: rds.registry.ksyun.com/common/net-tools:latest
    resources:
      requests:
        cpu: 2000m
        memory: 1000Mi
      limits:
        cpu: 3000m
        memory: 2000Mi
    command:
      - tail
      - -f
      - /dev/null