apiVersion: v1
kind: Pod
metadata:
  name: pod-test4
spec:
  shareProcessNamespace: true
  containers:
  - name: pod-test4
    image: rds.registry.ksyun.com/common/net-tools:latest
    command:
      - tail
      - -f
      - /dev/null