apiVersion: v1
kind: Pod
metadata:
  name: pod-test4
spec:
  shareProcessNamespace: true
  containers:
  - name: pod-test4
    image: rds.registry.ksyun.com/common/net-tools:latest
    resources:
      requests:
        cpu: 2000m
        memory: 1000Mi
        ephemeral-storage: 10Gi
      limits:
        cpu: 2000m
        memory: 1000Mi
        ephemeral-storage: 10Gi
    command:
      - tail
      - -f
      - /dev/null