apiVersion: v1
kind: Pod
metadata:
  name: pod-test5
spec:
  shareProcessNamespace: true
  containers:
  - name: pod-test4
    image: rds.registry.ksyun.com/common/net-tools:latest
    resources:
      limits:
        cpu: 2000m
        memory: 1000Mi
        ephemeral-storage: 200Gi
    command:
      - tail
      - -f
      - /dev/null
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir: {}
  nodeSelector:
    kubernetes.io/hostname: 10.0.2.116
